fastenhealth/fasten-onprem

backend/pkg/database/interface.go, backend/pkg/database/sqlite_repository.go, backend/pkg/models/glossary.go, backend/pkg/models/medlineplus_connect_results.go, backend/pkg/web/handler/glossary.go, backend/pkg/web/server.go, frontend/src/app/components/glossary-lookup/glossary-lookup.component.html, frontend/src/app/components/glossary-lookup/glossary-lookup.component.scss, frontend/src/app/components/glossary-lookup/glossary-lookup.component.spec.ts, frontend/src/app/components/glossary-lookup/glossary-lookup.component.ts, frontend/src/app/components/report-labs-observation/report-labs-observation.component.html, frontend/src/app/components/report-medical-history-condition/report-medical-history-condition.component.html, frontend/src/app/components/shared.module.ts, frontend/src/app/pages/resource-detail/resource-detail.component.html, frontend/src/app/pages/resource-detail/resource-detail.component.ts, frontend/src/app/services/fasten-api.service.ts, frontend/src/lib/models/resources/condition-model.ts
TODO list:
- The following **DIDN'T** work
- ellipsis-angular
- https://github.com/lentschi/ngx-ellipsis
- https://github.com/chaodyz/ngx-line-truncation
- https://github.com/lentschi/ngx-nested-ellipsis
- https://github.com/yowainwright/shave
- The following has not been tried
- https://github.com/NetanelBasal/angular2-shave
fixes #46
=> adding a glossary endpoint which attempts to get patient-friendly descriptions from code.

CONTRIBUTING.md, backend/pkg/database/sqlite_repository.go, frontend/angular.json, frontend/package.json, frontend/src/app/components/fhir/datatypes/dicom/dicom.component.html, frontend/src/app/components/fhir/datatypes/dicom/dicom.component.scss, frontend/src/app/components/fhir/datatypes/dicom/dicom.component.spec.ts, frontend/src/app/components/fhir/datatypes/dicom/dicom.component.ts, frontend/src/app/components/fhir/fhir-resource/fhir-resource.component.ts, frontend/src/app/components/fhir/resources/binary/binary.component.html, frontend/src/app/components/fhir/resources/binary/binary.component.spec.ts, frontend/src/app/components/fhir/resources/binary/binary.component.ts, frontend/src/app/components/fhir/resources/document-reference/document-reference.component.html, frontend/src/app/components/fhir/resources/media/media.component.html, frontend/src/app/components/fhir/resources/media/media.component.spec.ts, frontend/src/app/components/fhir/resources/media/media.component.ts, frontend/src/app/components/glossary-lookup/glossary-lookup.component.spec.ts, frontend/src/app/components/shared.module.ts, frontend/src/app/pages/resource-creator/resource-creator.utilities.ts, frontend/src/app/services/fasten-api.service.ts, frontend/src/lib/models/constants.ts, frontend/src/lib/models/datatypes/attachment-model.ts, frontend/src/lib/models/factory.ts, frontend/src/lib/models/resources/condition-model.spec.ts, frontend/src/lib/models/resources/document-reference-model.spec.ts, frontend/src/lib/models/resources/document-reference-model.ts, frontend/src/lib/models/resources/media-model.ts, frontend/yarn.lock, go.mod, go.sum
fixes #39 
[dicom_viewer_0012.zip](https://github.com/fastenhealth/fasten-onprem/files/11063757/dicom_viewer_0012.zip)
test file attached to this PR - extract it first. 
The relevant files that my be broken are here:
- [frontend/src/app/components/fhir/datatypes/dicom/dicom.component.ts](https://github.com/fastenhealth/fasten-onprem/blob/dicom_viewer/frontend/src/app/components/fhir/datatypes/dicom/dicom.component.ts)
- Lines 144-149
- Lines 297-303 
- [frontend/src/app/components/fhir/datatypes/dicom/dicom.component.html](https://github.com/fastenhealth/fasten-onprem/blob/dicom_viewer/frontend/src/app/components/fhir/datatypes/dicom/dicom.component.html)
- [frontend/src/lib/models/resources/binary-model.ts](https://github.com/fastenhealth/fasten-onprem/blob/dicom_viewer/frontend/src/lib/m …
=> started working on DICOM support (stored in Media object)

Dockerfile
Allows things like traefik to automatically discover the appropriate port and forward traffic to it.
=> Expose the web port in docker

backend/pkg/constants.go, backend/pkg/database/interface.go, backend/pkg/database/sqlite_repository.go, backend/pkg/database/sqlite_repository_graph.go, backend/pkg/web/handler/resource_fhir.go, backend/pkg/web/server.go, frontend/src/app/pages/medical-history/medical-history.component.ts, frontend/src/app/services/fasten-api.service.ts
(rather than at insertion time)
=> make sure we can dynamically generate directed graph relationships on demand

Makefile, backend/pkg/web/server.go, frontend/angular.json, frontend/src/app/app-routing.module.ts, frontend/src/app/components/medical-sources-connected/medical-sources-connected.component.ts, frontend/src/app/services/lighthouse.service.ts, frontend/src/environments/environment.cloud_sandbox.ts, frontend/src/environments/environment.desktop_sandbox.ts, frontend/src/environments/environment.prod.ts, frontend/src/environments/environment.sandbox.ts, frontend/src/environments/environment.ts
Added method to use embedded frontend routing.
rename desktop config to desktop_sandbox config.
adding desktop_mode (used for Wails Desktop app + hash based routing) make sure all `window.location` parsing works correctly with desktop_mode
=> split frontend routing config from backend config.

frontend/src/app/app-routing.module.ts, frontend/src/app/app.component.ts, frontend/src/app/app.module.ts, frontend/src/app/components/footer/footer.component.html, frontend/src/app/components/glossary-lookup/glossary-lookup.component.html, frontend/src/app/components/glossary-lookup/glossary-lookup.component.ts, frontend/src/app/components/list-generic-resource/list-generic-resource.component.html, frontend/src/app/components/shared.module.ts, frontend/src/app/directives/directives.module.ts, frontend/src/app/directives/external-link.directive.spec.ts, frontend/src/app/directives/external-link.directive.ts, frontend/src/app/pages/auth-signup/auth-signup.component.html, frontend/src/app/pages/dashboard/dashboard.component.html, frontend/src/app/pages/desktop-callback/desktop-callback.component.html, frontend/src/app/pages/desktop-callback/desktop-callback.component.spec.ts, frontend/src/app/pages/desktop-callback/desktop-callback.component.ts, frontend/src/app/pages/medical-sources/medical-sources.component.html, frontend/src/app/pages/medical-sources/medical-sources.component.ts, frontend/src/app/pages/resource-creator/resource-creator.component.html, frontend/src/app/services/lighthouse.service.ts, frontend/src/environments/environment.desktop_prod.ts, frontend/src/environments/environment.desktop_sandbox.ts, frontend/src/lib/utils/external_link.ts, frontend/src/polyfills.ts
- ensure that all external links open in an external window.
- connecting a new healthcare source will open an external window in desktop mode
- added a new desktop callback page specifically to emit Wails events (close external window & pass payload information back to main window)
=> desktop enhancements

backend/pkg/models/database/fhir_patient_test.go
Added unit test to validate the SearchExtractParameters for identifier and telecom attributes of the patient model using example 1 as input data.
=> update FhirPatient test to validate identifier and telecom for example1

backend/pkg/web/handler/source.go
While testing this app, I encountered an error. Looking at the logs, and there is a typo.
> time="2023-11-04T22:25:15Z" level=warning msg="This client requires a dynamice client registration, starting registration process" type=web
=> Spleling fix

backend/pkg/models/database/fhir_observation_test.go
Added unit testing for the fields in fhir_observation.go file. Still need to test the ones that have a subpath in their definitions example: ComboValueQuantity, Observation Encounter, Subject, ValueQuantity.
=> update FhirObservation unit tests

backend/pkg/models/database/fhir_patient_test.go, frontend/src/lib/fixtures/r4/resources/patient/example1.json
Added unit testing for the untested fields in fhir_patient.go. Only deceasedBoolean left to test now. Added To Do for the Goja parsing issue.
Changed the deceasedBoolean field in example1.json to true, as False (being default) does not show the correct testing behavior.
=> update FhirPatient unit tests for most fields

backend/pkg/web/handler/cors_proxy.go, backend/pkg/web/server.go, frontend/src/app/services/lighthouse.service.ts, go.mod, go.sum
- Includes fixes for Athena CORS proxy requirement.
- Handle cors_relay_required = true for Providers in UI. Added a safe CORS Proxy, which support for Whitelisted endpoints only.
- bump fasten-sources version. 
fixes #396 
fixes #376
fixes #249
=> CORS Proxy for Athena providers

README.md, TODO.md
Fixes #401 by removing the invalid character & missing command that prevent the install command from running from the Windows command line.
=> Updated install instructions for new users/Windows

frontend/src/app/widgets/patient-vitals-widget/patient-vitals-widget.component.ts
On the homepage dashboard to the right, where it says [Patient Name] | [Age] years | Gender:
- A patient birthdate of, for example, "2000-08-01" will incorrectly return **24 years** on the homepage
- It should return the correct age **23 years** (since the birthday has not passed yet this year). 
I believe this was an issue because it was somehow parsing the year but not the month and day of the `birthDate`, at least when there are multiple patient objects in the DB. 
Check if it is an array before calculating age. 
It is not an issue in `SourceDetailComponent`'s function `getPatientAge()`, because that uses a flattener helper method `getPath()`. I can centralize this logic instead in the PR, if you'd like.
=> Fix date display

CONTRIBUTING.md, frontend/src/app/components/fhir-card/datatypes/rtf/rtf.component.spec.ts, frontend/src/app/components/medical-record-wizard-add-lab-results/medical-record-wizard-add-lab-results.component.spec.ts, frontend/src/app/directives/image-fallback.directive.spec.ts, frontend/src/app/pages/auth-signup-wizard/auth-signup-wizard.component.spec.ts, frontend/src/app/services/platform.service.spec.ts
Small PR to fix the failing frontend tests. I also added a few small changes in CONTRIBUTING.md for things I came across while getting the repo up and running.
- Added a few small comments/clarifications to CONTRIBUTING.md for things that gave me a tiny pause setting up
- Updated failing frontend tests. Mostly adding providers and imports to the TestBed configuration in the tests.
=> Fix frontend tests

frontend/.storybook/main.ts, frontend/src/app/directives/image-fallback.directive.ts
So I noticed that in the Storybook upload off of main that the medical sources card component is erroring out and it isn't able to generate snapshots. When I click into it on the website it seems like there are two problems: 
1) The assets aren't getting added to the storybook upload causing the fallback image not to be found. 
2) The image fallback directive is trapped in an endless loop looking for the fallback image.
I found some [docs](https://storybook.js.org/docs/configure/images-and-assets#serving-static-files-via-storybook-configuration) saying that serving static assets via Storybook configuration is recommended so I've tried adding that configuration. I'm not sure if it will work, or if this is what is causing the component error making the build fail, but I figured it was worth …
=> Prevent possible endless loop with image fallback

frontend/src/app/components/glossary-lookup/glossary-lookup.component.scss, frontend/src/app/components/glossary-lookup/glossary-lookup.stories.ts, frontend/src/app/components/report-labs-observation/report-labs-observation.stories.ts
On the labs page, sometimes the glossary overflows horizontally. I've added `max-width: 100%` to limit it to the width of the parent element. Fixes #408
Sometimes the 
- add `max-width: 100%` to the glossary-lookup scss
- add story to glossary lookup stories and add report labs observation story
=> Fix horizontal overflow for glossary lookup

frontend/src/app/components/fhir-card/common/table/table.component.html, frontend/src/app/components/fhir-card/common/table/table.component.spec.ts, frontend/src/app/components/fhir-card/common/table/table.stories.ts, frontend/src/app/components/fhir-card/resources/allergy-intolerance/allergy-intolerance.component.html, frontend/src/app/components/fhir-card/resources/diagnostic-report/diagnostic-report.component.html, frontend/src/app/components/fhir-card/resources/document-reference/document-reference.component.html, frontend/src/app/components/fhir-card/resources/encounter/encounter.component.html, frontend/src/app/components/fhir-card/resources/immunization/immunization.component.html, frontend/src/app/components/fhir-card/resources/location/location.component.html, frontend/src/app/components/fhir-card/resources/media/media.component.html, frontend/src/app/components/fhir-card/resources/medication-request/medication-request.component.html, frontend/src/app/components/fhir-card/resources/medication/medication.component.html, frontend/src/app/components/fhir-card/resources/observation/observation.component.html, frontend/src/app/components/fhir-card/resources/organization/organization.component.html, frontend/src/app/components/fhir-card/resources/practitioner/practitioner.component.html, frontend/src/app/components/fhir-card/resources/procedure/procedure.component.html, frontend/src/app/components/fhir-datatable/fhir-datatable/fhir-datatable.component.ts, frontend/src/app/components/medical-sources-connected/medical-sources-connected.component.html, frontend/src/app/components/report-labs-observation/report-labs-observation.component.html, frontend/src/app/components/report-medical-history-condition/report-medical-history-condition.component.html, frontend/src/app/components/report-medical-history-explanation-of-benefit/report-medical-history-explanation-of-benefit.component.html, frontend/src/app/components/report-medical-history-timeline-panel/report-medical-history-timeline-panel.component.html, frontend/src/app/pages/dashboard/dashboard.component.ts, frontend/src/app/pages/explore/explore.component.ts, frontend/src/app/pages/resource-detail/resource-detail.component.html, frontend/src/app/pages/source-detail/source-detail.component.html
Fixes #437. Its possible for ids to include non-url-safe characters. Since these ids are being interpolated into a url string without encoding, it is causing the url to fail. 
To fix this, I've updated the code so that we are passing urls as arrays of strings rather than an interpolated string. By passing as an array of strings, the built in router knows to encode each string if needed.
There were a few places in components where we were using `navigateByUrl` with an interpolated string. `navigateByUrl` doesn't accept an array of strings so I've switched those few places to use `navigate`. I'm not sure if there was a specific reason for using `navigateByUrl` over `navigate` in those spots. If there is a need to use `navigateByUrl` please let me know and I will update those spots to …
=> Fix URL encoding issue for links

frontend/src/app/components/fhir-card/common/observation-bar-chart/observation-bar-chart.component.ts, frontend/src/app/components/fhir-card/common/observation-bar-chart/observation-bar-chart.stories.ts, frontend/src/lib/fixtures/factories/r4/resources/observation-r4-factory.ts, frontend/src/lib/models/resources/observation-model.spec.ts, frontend/src/lib/models/resources/observation-model.ts
Right now lab values that have a `<` are parsed as 0. This PR adds some quick parsing so that these are displayed like reference ranges are. 
Fixes #441
- Update observation model to check for ranged values in valueString and the comparator attribute in valueQuantity and return a `ValueObject`
- Update bar chart to use new `ValueObject` for values instead of `value_quantity_value`
- Normally I would fully remove this value, but I am leaving it for now because it is used in places that I'll be updating soon as part of my changes to address #360. 
- Add `valueQuantity` trait to observation factory to allow custom values
- Added an observation bar chart story to test display of a ranged value
- Note: The tooltip is a little wonky with the text display and the color of the result is a little …
=> Parse lab values that include a range

frontend/src/app/pages/source-detail/source-detail.component.html, frontend/src/app/pages/source-detail/source-detail.component.ts
- hide image if there is no brand
- show complete address
- use the source id instead of endpoint_id in breadcrumbs
=> cleanup source detail page

frontend/src/app/pages/background-jobs/background-jobs.component.html
Without this, the background jobs page shows "Invalid date" if there's a job running.
=> don't show date if the job isn't done

.github/workflows/development.yaml
CI is currently broken due to a deprecated github action. This upgrades the action to the latest version.
=> use upload-artifact v4 to fix CI

.devcontainer/devcontainer.json
Adds a devcontainer to make development work easier for new people. This will let you open up a container image based on debian that has node 20, go 1.21 and the latest stable chrome version. I tested with make test and i got the same 1 frontend error that the CI is also getting.
=> Add initial devcontainer
